# Generated by Django 6.0.7 on 2026-08-19 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('OTHER', '다른 옵션'), ('FITTING', '착용 상담'), ('STYLING', '스타일링'), ('ETC', '기타')], max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('REQUESTED', '요청'), ('IN_PROGRESS', '상담 중'), ('COMPLETED', '완료')], default='REQUESTED', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_requests', to='products.product')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_requests', to='recommendations.visitsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
