# Generated by Django 6.0.7 on 2026-08-15 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('recommendations', '0002_look_lookitem_recommendationresult_savedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrequest',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_requests', to='recommendations.visitsession'),
            preserve_default=False,
        ),
    ]
