# Generated by Django 6.0.7 on 2026-08-16 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrequest',
            name='session_key',
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_requests', to='recommendations.visitsession'),
        ),
    ]
