# Generated by Django 6.0.7 on 2026-08-15 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_businesshours_material_materialproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VisitSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StyleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('style_chips', models.ManyToManyField(related_name='style_profiles', to='recommendations.stylechip')),
                ('visit_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style_profile', to='recommendations.visitsession')),
            ],
        ),
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('look_order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('reason', models.TextField()),
                ('style_chip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='looks', to='recommendations.stylechip')),
                ('style_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looks', to='recommendations.styleprofile')),
            ],
            options={
                'ordering': ['look_order'],
            },
        ),
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_histories', to='products.product')),
                ('visit_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='recommendations.visitsession')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='LookProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('TOP', 'Top'), ('BOTTOM', 'Bottom'), ('SHOES', 'Shoes'), ('BAG', 'Bag'), ('ACCESSORY', 'Accessory')], max_length=20)),
                ('source', models.CharField(choices=[('VISITED', 'Visited Product'), ('RECOMMENDED', 'AI Recommended')], max_length=20)),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='look_products', to='recommendations.look')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='look_products', to='products.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('look', 'product'), name='unique_product_per_look'), models.UniqueConstraint(fields=('look', 'item_type'), name='unique_item_type_per_look')],
            },
        ),
        migrations.AddConstraint(
            model_name='look',
            constraint=models.UniqueConstraint(fields=('style_profile', 'look_order'), name='unique_look_order_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='look',
            constraint=models.UniqueConstraint(fields=('style_profile', 'style_chip'), name='unique_style_chip_per_profile_look'),
        ),
    ]
