# Generated by Django 6.0.7 on 2026-08-10 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_alter_branch_id_alter_collection_id_alter_nfctag_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_histories', to='products.product')),
                ('visit_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='recommendations.visitsession')),
            ],
        ),
        migrations.CreateModel(
            name='StyleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('analysis_mode', models.CharField(choices=[('BEHAVIOR', '탐색 행동 기반'), ('SINGLE_PRODUCT', '단일 제품 기반')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style_profile', to='recommendations.visitsession')),
            ],
        ),
    ]
