# Generated by Django 6.0.7 on 2026-08-16 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_businesshours_close_alter_businesshours_open'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='styleprofile',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='style_profiles', to='products.product'),
        ),
        migrations.AlterField(
            model_name='styleprofile',
            name='visit_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_profiles', to='recommendations.visitsession'),
        ),
    ]
