# Generated by Django 6.0.7 on 2026-08-12 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcategory_product_category'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('look_order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('reason', models.TextField()),
                ('style_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looks', to='recommendations.styleprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('type', models.CharField(blank=True, max_length=50)),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recommendations.look')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SIMILAR', 'Similar'), ('NEW', 'New')], max_length=20)),
                ('reason', models.TextField()),
                ('score', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('style_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.styleprofile')),
            ],
            options={
                'ordering': ['score'],
            },
        ),
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('visit_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_products', to='recommendations.visitsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('visit_session', 'product'), name='unique_saved_product_per_session')],
            },
        ),
    ]
