# Generated by Django 6.0.7 on 2026-08-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='look',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='looks/'),
        ),
    ]
