# Generated by Django 6.0.7 on 2026-08-16 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_businesshours_close_alter_businesshours_open'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_sessions', to='products.product')),
                ('visit_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_products', to='recommendations.visitsession')),
            ],
            options={
                'ordering': ['-saved_at'],
                'constraints': [models.UniqueConstraint(fields=('visit_session', 'product'), name='unique_saved_product_per_session')],
            },
        ),
    ]
