# Generated by Django 6.0.7 on 2026-08-11 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_branch_id_alter_collection_id_alter_nfctag_id_and_more'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StylingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('look_order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('reason', models.TextField()),
                ('style_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styling_results', to='recommendations.styleprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StylingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('type', models.CharField(blank=True, max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('styling_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recommendations.stylingresult')),
            ],
        ),
    ]
