# Generated by Django 6.0.7 on 2026-08-14 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_material_alter_branch_latitude_and_more'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='styleprofile',
            old_name='tags',
            new_name='style_chips',
        ),
        migrations.RemoveField(
            model_name='styleprofile',
            name='analysis_mode',
        ),
        migrations.AddField(
            model_name='visitsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('look_order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reason', models.TextField()),
                ('style_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looks', to='recommendations.styleprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LookProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='look_products', to='recommendations.look')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='look_products', to='products.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('look', 'product'), name='unique_product_per_look')],
            },
        ),
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='unique_saved_product_per_user')],
            },
        ),
    ]
