# Generated by Django 6.0.7 on 2026-08-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_look_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='look',
            name='image_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
