# Generated by Django 6.0.7 on 2026-08-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_rename_tags_styleprofile_style_chips_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='look',
            options={'ordering': ['look_order']},
        ),
        migrations.AlterModelOptions(
            name='visithistory',
            options={'ordering': ['sequence']},
        ),
        migrations.AddField(
            model_name='look',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RemoveField(
            model_name='styleprofile',
            name='style_chips',
        ),
        migrations.AddField(
            model_name='look',
            name='style_chips',
            field=models.ManyToManyField(related_name='looks', to='recommendations.stylechip'),
        ),
        migrations.AddConstraint(
            model_name='look',
            constraint=models.UniqueConstraint(fields=('style_profile', 'look_order'), name='unique_look_order_per_profile'),
        ),
        migrations.AddField(
            model_name='styleprofile',
            name='style_chips',
            field=models.ManyToManyField(related_name='style_profiles', to='recommendations.stylechip'),
        ),
    ]
