# Generated by Django 6.0.7 on 2026-08-11 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_branch_id_alter_collection_id_alter_nfctag_id_and_more'),
        ('recommendations', '0002_stylingresult_stylingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SIMILAR', 'Similar'), ('NEW', 'New')], max_length=20)),
                ('reason', models.TextField()),
                ('score', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('style_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.styleprofile')),
            ],
            options={
                'ordering': ['score'],
            },
        ),
    ]
