# Generated by Django 6.0.7 on 2026-08-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_savedproduct'),
        ('recommendations', '0002_styleprofile_main_product_and_more'),
    ]

    operations = [
    ]
