# Generated by Django 6.0.7 on 2026-08-18 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_style_no_productdetail_style_no'),
        ('recommendations', '0003_merge_20260817_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleprofile',
            name='main_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='style_profiles', to='products.product'),
        ),
    ]
