# Generated by Django 6.0.7 on 2026-08-11 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_recommendationresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendationresult',
            options={'ordering': ['rank']},
        ),
        migrations.RenameField(
            model_name='recommendationresult',
            old_name='score',
            new_name='rank',
        ),
    ]
