# Generated by Django 6.0.7 on 2026-08-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_material_alter_branch_latitude_and_more'),
        ('recommendations', '0003_stylechip_alter_look_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookproduct',
            name='item_type',
            field=models.CharField(choices=[('TOP', 'Top'), ('BOTTOM', 'Bottom'), ('ACCESSORY', 'Accessory'), ('SHOES', 'Shoes'), ('BAG', 'Bag')], default='BAG', max_length=20),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='lookproduct',
            constraint=models.UniqueConstraint(fields=('look', 'item_type'), name='unique_item_type_per_look'),
        ),
    ]
