# Generated by Django 6.0.7 on 2026-08-11 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_alter_recommendationresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendationresult',
            options={'ordering': ['score']},
        ),
        migrations.RenameField(
            model_name='recommendationresult',
            old_name='rank',
            new_name='score',
        ),
    ]
