# Generated by Django 6.0.7 on 2026-08-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_alter_styleprofile_main_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookproduct',
            name='item_type',
            field=models.CharField(choices=[('TOP', 'Top'), ('BOTTOM', 'Bottom'), ('SHOES', 'Shoes'), ('BAG', 'Bag'), ('ACCESSORY', 'Accessory')], editable=False, max_length=20),
        ),
    ]
