# Generated by Django 6.0.7 on 2026-08-12 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_branch_id_alter_collection_id_alter_nfctag_id_and_more'),
        ('recommendations', '0005_alter_recommendationresult_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('visit_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_products', to='recommendations.visitsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('visit_session', 'product'), name='unique_saved_product_per_session')],
            },
        ),
    ]
