# Generated by Django 6.0.7 on 2026-08-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_specs_careguide_material_story_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='location',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
