# Generated by Django 6.0.7 on 2026-08-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_businesshours_material_materialproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='style_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('branch', 'detail'), name='unique_branch_detail_stock'),
        ),
    ]
