# Generated by Django 6.0.7 on 2026-08-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_style_no_alter_product_specs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshours',
            name='close',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='open',
            field=models.TimeField(),
        ),
    ]
