# Generated by Django 6.0.7 on 2026-08-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_businesshours_close_alter_businesshours_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='style_no',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='style_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
