# Generated by Django 6.0.7 on 2026-08-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_style_no_productdetail_style_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='style_no',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TOP', 'Top'), ('BOTTOM', 'Bottom'), ('SHOES', 'Shoes'), ('BAG', 'Bag'), ('ACCESSORY', 'Accessory')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
