# Generated by Django 6.0.7 on 2026-08-14 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_businesshours_productdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshours',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='products.branch'),
        ),
    ]
